export const VAULT_ABI = [
  { type: "function", name: "balanceOf", stateMutability: "view",
    inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "scansPaid", stateMutability: "view",
    inputs: [{ name: "user", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "cardRegistered", stateMutability: "view",
    inputs: [{ name: "user", type: "address" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "cardNumber", stateMutability: "pure",
    inputs: [{ name: "user", type: "address" }], outputs: [{ type: "string" }] },
  { type: "function", name: "addressFromCardNumber", stateMutability: "view",
    inputs: [{ name: "cardNum", type: "string" }], outputs: [{ type: "address" }] },
  { type: "function", name: "cardInfo", stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [
      { name: "balance", type: "uint256" },
      { name: "scans", type: "uint256" },
      { name: "scanCost", type: "uint256" },
      { name: "registered", type: "bool" },
      { name: "myCardNumber", type: "string" },
    ] },
  { type: "function", name: "SCAN_COST", stateMutability: "view",
    inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "deposit", stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "payForScan", stateMutability: "nonpayable",
    inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "withdrawAll", stateMutability: "nonpayable",
    inputs: [], outputs: [] },
  { type: "function", name: "registerCard", stateMutability: "nonpayable",
    inputs: [], outputs: [] },
  { type: "function", name: "transferInVault", stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "memo", type: "string" },
    ], outputs: [] },
  { type: "function", name: "transferByCardNumber", stateMutability: "nonpayable",
    inputs: [
      { name: "cardNum", type: "string" },
      { name: "amount", type: "uint256" },
      { name: "memo", type: "string" },
    ], outputs: [] },
] as const;

export const USDC_ABI = [
  { type: "function", name: "balanceOf", stateMutability: "view",
    inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }] },
] as const;
